### ISSUE TITLE
util.cc build errors with clang++-3.6 (fuzzing)

### ISSUE THREAD

**Issue by 64616E69656C** [tatsuhiro-t/nghttp2#284]
Hi,

First things first, your code quality is amazing. 
I switched my packaging/build system from gcc to clang-3.6, first fuzzing, then building.

It builds perfectly with clang 3.6 and default C[XX]FLAGS, but when fuzzing with clang++-3.6 (./configure CFLAGS="-fsanitize=address,undefined -Wformat -Werror=format-security -Warray-bounds -Werror=array-bounds -Wshorten-64-to-32 -g" CXXFLAGS="-fsanitize=address,undefined -Wformat -Werror=format-security -Warray-bounds -Werror=array-bounds -Wshorten-64-to-32 -g" LDFLAGS="-fsanitize=address,undefined -Wshorten-64-to-32" CC="clang-$LLVM_VERSION" CXX="clang++-$LLVM_VERSION"), building fails at util.cc

```
make[3]: Entering directory '/home/daniel/code/nghttp2/nghttp2-1.0.5.orig/src'
  CXX      util.o
In file included from util.cc:25:
In file included from ./util.h:42:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/string:52:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/basic_string.h:2849:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/ext/string_conversions.h:41:
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/cstdlib:140:11: error: no member named 'malloc' in the global namespace
  using ::malloc;
        ~~^
In file included from util.cc:25:
In file included from ./util.h:43:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/algorithm:62:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/stl_algo.h:66:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/random:50:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9/bits/opt_random.h:33:
In file included from /usr/lib/llvm-3.6/bin/../lib/clang/3.6.2/include/x86intrin.h:29:
In file included from /usr/lib/llvm-3.6/bin/../lib/clang/3.6.2/include/immintrin.h:32:
In file included from /usr/lib/llvm-3.6/bin/../lib/clang/3.6.2/include/xmmintrin.h:40:
/usr/lib/llvm-3.6/bin/../lib/clang/3.6.2/include/mm_malloc.h:49:12: error: use of undeclared identifier 'malloc'; did you mean 'valloc'?
    return malloc(__size);
           ^
/usr/include/stdlib.h:498:14: note: 'valloc' declared here
extern void *valloc (size_t __size) __THROW __attribute_malloc__ __wur;
             ^
util.cc:287:24: warning: implicit conversion loses integer precision: 'long' to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
  p = cpydig(p, gmtoff / 3600, 2);
      ~~~~~~    ~~~~~~~^~~~~~
util.cc:341:26: warning: implicit conversion loses integer precision: 'long' to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
    p = cpydig(p, gmtoff / 3600, 2);
        ~~~~~~    ~~~~~~~^~~~~~
util.cc:566:29: warning: implicit conversion loses integer precision: 'long' to 'int' [-Wshorten-64-to-32]
        levenshtein(unkopt, unkoptlen, options[i].name, optnamelen, 0, 2, 1, 3);
        ~~~~~~~~~~~         ^~~~~~~~~
util.cc:566:57: warning: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Wshorten-64-to-32]
        levenshtein(unkopt, unkoptlen, options[i].name, optnamelen, 0, 2, 1, 3);
        ~~~~~~~~~~~                                     ^~~~~~~~~~
4 warnings and 2 errors generated.
Makefile:1326: recipe for target 'util.o' failed
make[3]: *** [util.o] Error 1
```

That's weird, because stdlib.h is being used. Is this more likely LLVM related?

And again, it builds fine with afl-clang++ (clang 3.5.2), same CFLAGS as above.

```
make[3]: Entering directory '/home/daniel/code/nghttp2/nghttp2-1.0.5.orig/src'
  CXX      util.o
afl-cc 1.83b by <lcamtuf@google.com>
util.cc:287:24: warning: implicit conversion loses integer precision: 'long' to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
  p = cpydig(p, gmtoff / 3600, 2);
      ~~~~~~    ~~~~~~~^~~~~~
util.cc:341:26: warning: implicit conversion loses integer precision: 'long' to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
    p = cpydig(p, gmtoff / 3600, 2);
        ~~~~~~    ~~~~~~~^~~~~~
util.cc:566:29: warning: implicit conversion loses integer precision: 'long' to 'int' [-Wshorten-64-to-32]
        levenshtein(unkopt, unkoptlen, options[i].name, optnamelen, 0, 2, 1, 3);
        ~~~~~~~~~~~         ^~~~~~~~~
util.cc:566:57: warning: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Wshorten-64-to-32]
        levenshtein(unkopt, unkoptlen, options[i].name, optnamelen, 0, 2, 1, 3);
        ~~~~~~~~~~~                                     ^~~~~~~~~~
4 warnings generated.
afl-as 1.83b by <lcamtuf@google.com>
[+] Instrumented 6547 locations (64-bit, non-hardened mode, ratio 100%).
```

**Comment by tatsuhiro-t** [comment]
I think 580c1f3 fixes this issue.  `autoreconf` should be run to re-generate autotool files.

**Comment by 64616E69656C** [comment]
fix confirmed, closing this.
