### ISSUE TITLE
nghttp2 1.2.1 make failed after upgrade openssl 1.0.2d

### ISSUE THREAD

**Issue by paramarines** [tatsuhiro-t/nghttp2#336]
After I upgrade openssl to 1.0.2d
make nghttp2 1.2.1 it report:
nghttp.o: In function `nghttp2::HttpClient::connection_made()':
/tmp/nghttp2-1.2.1/src/nghttp.cc:951: undefined reference to `SSL_get0_alpn_selected'
/tmp/nghttp2-1.2.1/src/nghttp.cc:951: undefined reference to `SSL_get0_alpn_selected'
nghttp.o: In function `communicate':
/tmp/nghttp2-1.2.1/src/nghttp.cc:2047: undefined reference to `SSL_CTX_set_alpn_protos'
collect2: error: ld returned 1 exit status
make[3]: *** [nghttp] Error 1

When I upgrade openssl, I ever updated the dynamic link library w/.
echo "/usr/local/ssl/lib" >> /etc/ld.so.conf
ldconfig -v

I checked my libssl.so.1.0.0
root@Nghttp2:/usr/local/ssl/lib# nm libssl.so.1.0.0 | grep SSL_CTX_set_alpn_protos
00000000000499c0 T SSL_CTX_set_alpn_protos
root@Nghttp2:/usr/local/ssl/lib# nm libssl.so.1.0.0 | grep SSL_get0_alpn_selected
0000000000049a90 T SSL_get0_alpn_selected

**Comment by tatsuhiro-t** [comment]
I think https://github.com/tatsuhiro-t/nghttp2/issues/327#issuecomment-130346827 is related.
Please make sure that PKG_CONFIG_PATH is given correctly to configure script.

**Comment by paramarines** [comment]
@tatsuhiro-t We have used the correct ssl header file, the error occurred at link `SSL_get0_alpn_selected' and `SSL_CTX_set_alpn_protos'

**Comment by tatsuhiro-t** [comment]
I think that linker option was not set correctly to see the custom openssl installation.
Could you tell us the configure command line options you specified when this particular issue occured?

**Comment by paramarines** [comment]
For openssl
    
    ./config shared zlib && make && make install
    mv /usr/bin/openssl /usr/bin/openssl.old
    mv /usr/include/openssl /usr/include/openssl.old
    ln -s /usr/local/ssl/bin/openssl /usr/bin/openssl
    ln -s /usr/local/ssl/include/openssl /usr/include/openssl
    echo "/usr/local/ssl/lib" >> /etc/ld.so.conf
    ldconfig -v

For nghttp2
    
    ./configure --enable-asio-lib && make
    configure: summary of build options:

    Version:        1.2.1 shared 14:8:0
    Host type:      x86_64-unknown-linux-gnu
    Install prefix: /usr/local
    C compiler:     gcc
    CFLAGS:         -g -O2
    WARNCFLAGS:     
    LDFLAGS:        
    LIBS:           
    CPPFLAGS:       
    C preprocessor: gcc -E
    C++ compiler:   g++
    CXXFLAGS:       -g -O2 -std=c++11
    CXXCPP:         g++ -E
    Library types:  Shared=yes, Static=yes
    Python:
      Python:         /usr/bin/python
      PYTHON_VERSION: 2.7
      pyexecdir:      ${exec_prefix}/lib/python2.7/dist-packages
      Python-dev:     yes
      PYTHON_CPPFLAGS:-I/usr/include/python2.7
      PYTHON_LDFLAGS: -L/usr/lib -lpython2.7
      Cython:         cython
    Test:
      CUnit:          yes
      Failmalloc:     yes
    Libs:
      OpenSSL:        yes
      Libxml2:        yes
      Libev:          yes
      Libevent(SSL):  yes
      Spdylay:        yes
      Jansson:        yes
      Jemalloc:       yes
      Zlib:           yes
      Boost CPPFLAGS: -pthread -I/usr/include
      Boost LDFLAGS:  -L/usr/lib/x86_64-linux-gnu
      Boost::ASIO:    -lboost_system
      Boost::System:  -lboost_system
      Boost::Thread:  -lboost_thread
    Features:
      Applications:   yes
      HPACK tools:    yes
      Libnghttp2_asio:yes
      Examples:       yes
      Python bindings:yes
      Threading:      yes
      Third-party:    yes

I found it always use the system old ssl library to complie. So I did some changes.

    cd /lib/x86_64-linux-gnu
    mv libssl.so.1.0.0 libssl.so.1.0.0.old
    mv libcrypto.so.1.0.0 libcrypto.so.1.0.0.old
    ln -s /usr/local/ssl/lib/libssl.so.1.0.0 libssl.so.1.0.0
    ln -s /usr/local/ssl/lib/libcrypto.so.1.0.0 libcrypto.so.1.0.0

For now the nghttp make successful but there is something wrong at make example
    
      CXXLD    nghttp
      CXX      nghttpd.o
      CXX      HttpServer.o
      CXXLD    nghttpd
      CXX      shrpx.o
      CXXLD    nghttpx
      CXX      h2load.o
      CXX      h2load_http2_session.o
      CXX      h2load_spdy_session.o
      CXXLD    h2load
      CXX      inflatehd.o
      CC       comp_helper.o
      CXXLD    inflatehd
      CXX      deflatehd.o
      CXXLD    deflatehd
    make[3]: Leaving directory `/home/nghttp2-1.2.1/src'
    make[2]: Leaving directory `/home/nghttp2-1.2.1/src'
    Making all in examples
    make[2]: Entering directory `/home/nghttp2-1.2.1/examples'
      CC       client.o
      CCLD     client
      CC       libevent-client.o
    libevent-client.c: In function 鈊elete_http2_session_data?
    libevent-client.c:161:3: warning: implicit declaration of function 鈈ufferevent_openssl_get_ssl?[-Wimplicit-function-declaration]
       SSL *ssl = bufferevent_openssl_get_ssl(session_data->bev);
       ^
    libevent-client.c:161:14: warning: initialization makes pointer from integer without a cast [enabled by default]
       SSL *ssl = bufferevent_openssl_get_ssl(session_data->bev);
                  ^
    libevent-client.c: In function 鈏nitiate_connection?
    libevent-client.c:506:3: warning: implicit declaration of function 鈈ufferevent_openssl_socket_new?[-Wimplicit-function-declaration]
       bev = bufferevent_openssl_socket_new(
       ^
    libevent-client.c:506:7: warning: assignment makes pointer from integer without a cast [enabled by default]
       bev = bufferevent_openssl_socket_new(
           ^
      CCLD     libevent-client
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `SSL_get_error@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `BIO_number_written@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `SSL_write@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `ERR_get_error@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `SSL_set_accept_state@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `BIO_new_socket@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `SSL_get_rbio@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `SSL_get_shutdown@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `SSL_set_connect_state@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `BIO_number_read@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `BIO_ctrl@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `SSL_get_wbio@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `BIO_new@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `SSL_ctrl@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `ERR_peek_error@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `BIO_clear_flags@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `SSL_set_bio@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `BIO_set_flags@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `SSL_do_handshake@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `SSL_free@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `SSL_renegotiate@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `SSL_read@OPENSSL_1.0.0'
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libevent_openssl.so: undefined reference to `SSL_pending@OPENSSL_1.0.0'
    collect2: error: ld returned 1 exit status
    make[2]: *** [libevent-client] Error 1
    make[2]: Leaving directory `/home/nghttp2-1.2.1/examples'
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory `/home/nghttp2-1.2.1'
    make: *** [all] Error 2

    root@Nghttp2:/home/nghttp2-1.2.1# nghttp --version
    nghttp nghttp2/1.2.1

**Comment by tatsuhiro-t** [comment]
If you don't need examples, use --disable-examples configure option to disable building examples.

The original error was because compiled custom openssl library files are not there in the expected directory: in this particular case, /usr/lib.
In general, I don't recommend to overwrite system installed openssl with custom openssl because many other packages may depend on the specific system installed openssl.
One of those package is libevent-openssl.  The above error message is generated because there is no openssl libevent-openssl package originally depends on.
If system install openssl version is at least 1.0.1, then I recommend to use it for now, since most browsers still support NPN.

**Comment by paramarines** [comment]
Thanks for your comments. I follow the step you provided:
    
    export PKG_CONFIG_PATH=/usr/local/ssl/lib/pkgconfig
    ./configure --enable-asio-lib --disable-examples
    make
Error occurred:
    
    Making all in examples
    make[2]: Entering directory `/home/nghttp2-1.2.1/examples'
    make[2]: Nothing to be done for `all'.
    make[2]: Leaving directory `/home/nghttp2-1.2.1/examples'
    Making all in python
    make[2]: Entering directory `/home/nghttp2-1.2.1/python'
    cython -o nghttp2.c nghttp2.pyx
    /usr/bin/python setup.py build
    Traceback (most recent call last):
      File "setup.py", line 24, in <module>
        from setuptools import setup, Extension
    ImportError: No module named setuptools
    make[2]: *** [all-local] Error 1
    make[2]: Leaving directory `/home/nghttp2-1.2.1/python'
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory `/home/nghttp2-1.2.1'
    make: *** [all] Error 2

**Comment by paramarines** [comment]
After install python-setuptools everything is ok.
Thank you!

**Comment by tatsuhiro-t** [comment]
Right, let's close the issue.
