### ISSUE TITLE
Build on ubuntu 12.04

### ISSUE THREAD

**Issue by weldpua2008** [tatsuhiro-t/nghttp2#174]
Hello,
I builded spdylay:  is not packaged in Ubuntu, so you need to build it yourself: http://tatsuhiro-t.github.io/spdylay/

I installed gcc 4.9/4.8 on Ubuntu 12.04 with http://askubuntu.com/questions/271388/how-to-install-gcc-4-8/271561#271561
(There are: https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test gcc 4.8.1/4.9.2)

But when I build nghttp2 there is error:
```
make[3]: Entering directory `/root/nghttp2/src'
  CXX    util.o
In file included from util.cc:47:0:
template.h:70:9: error: expected nested-name-specifier before ‘ResultType’
template.h:70:9: error: using-declaration for non-member at class scope
template.h:70:20: error: expected ‘;’ before ‘=’ token
template.h:70:20: error: expected unqualified-id before ‘=’ token
template.h:72:28: error: there are no arguments to ‘ResultType’ that depend on a template parameter, so a declaration of ‘ResultType’ must be available [-fpermissive]
template.h:72:28: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
template.h:72:29: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Signature> struct std::function’
template.h:72:29: error:   expected a type, got ‘ResultType()’
make[3]: *** [util.o] Error 1
make[3]: Leaving directory `/root/nghttp2/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/root/nghttp2/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/nghttp2'
make: *** [all] Error 2
```

**Comment by tatsuhiro-t** [comment]
These kind of error usually comes from compiler capable of c++11 is not properly invoked or installed.
Could you check that you really run g++-4.9 and it is correctly installed?

**Comment by tatsuhiro-t** [comment]
As far as I'm concerned, ubuntu 12.04 is a bit too old, since c++11 compiler grows rapidly these days.

**Comment by weldpua2008** [comment]
ubuntu LTS can has a new toolchain. What packages I need to upgrade?

**Comment by tatsuhiro-t** [comment]
nghttp2 can be built on Ubuntu 14.04 LTS, with standard clang-3.5.

**Comment by tatsuhiro-t** [comment]
Reopen issue if you still have this issue.

**Comment by p** [comment]
Travis still uses ubuntu 12.04 for container builds so not being able to build on that OS is a problem.

I succeeded in building nghttp2 1.6.0 with default settings on 12.04 but it looks like only the library got built, in particular util.cc was not compiled. This might be all that I need for now as I just want curl to have http2 support.

**Comment by tatsuhiro-t** [comment]
We use travis CI to build all binaries except for asio libs (which depends only massive libboost).
Check out https://github.com/tatsuhiro-t/nghttp2/blob/master/.travis.yml

**Comment by alagoutte** [comment]
You can update .travis to use 14.04
Only need to add 
dist: trusty

**Comment by tatsuhiro-t** [comment]
That is a good news.
It seems we cannot use 14.04 if we use container based build environment, since using 14.04 requires "sudo: required".  I hope container based one also gets 14.04 soon.

**Comment by tatsuhiro-t** [comment]
https://docs.travis-ci.com/user/ci-environment/

**Comment by alagoutte** [comment]
Yes  but why do you prefer container ?

**Comment by p** [comment]
That's good info, thanks!

**Comment by p** [comment]
@alagoutte container builds start much faster (several seconds instead of 1+ minute for non-container builds).

**Comment by alagoutte** [comment]
@p if it is only the speed to start... it is a minor for me ;-)

**Comment by p** [comment]
OK!
