### ISSUE TITLE
Plain Windows MSVC build supported?

### ISSUE THREAD

**Issue by remoe** [tatsuhiro-t/nghttp2#195]
Hi

The current build stack doesn't work with MSVC without install a Cygwin/MinGW stack. Why not support CMake at least for the nghttp2-lib?

**Comment by tatsuhiro-t** [comment]
We have Makefile.msvc
https://github.com/tatsuhiro-t/nghttp2/blob/master/lib/Makefile.msvc

It seems outdated now, but if added missing source files, I think it should work.

**Comment by remoe** [comment]
Thanks. I know, but it needs a lot of unix tools to build correct. (for example nm, grep, subst ...). CMake solves some issues without such shell tools. 

I've tried it with cygwin. I had errors at the end of ./configure, I've tried with VS2013:

```shell
...
checking consistency of all components of python development environment... no
configure: WARNING:
  Could not link test program to Python. Maybe the main Python library has been
  installed in some non-standard library path. If so, pass it to configure,
  via the LDFLAGS environment variable.
  Example: ./configure LDFLAGS="-L/usr/non-standard-path/python/lib"
  ============================================================================
   ERROR!
   You probably have to install the development version of the Python package
   for your distribution.  The exact name of this package varies among them.
  ============================================================================

checking for cython.py... no
checking for cython... no
checking whether cl.exe supports C++11 features by default... yes
checking whether std::chrono::steady_clock is available... yes
checking whether std::future is available... yes
checking whether std::map::emplace is available... yes
checking for library containing dlsym... no
checking for library containing clock_gettime... no
checking for ZLIB... yes
checking for CUNIT... no
configure: WARNING: No package 'cunit' found
checking for CU_initialize_registry in -lcunit... no
checking for ev_time in -lev... no
checking for OPENSSL... yes
checking for LIBEVENT_OPENSSL... no
configure: No package 'libevent_openssl' found
checking for JANSSON... no
configure: No package 'jansson' found
checking for xml2-config... /usr/bin/xml2-config
checking for libxml - version >= 2.7.7... no
*** Could not run libxml test program, checking why...
*** The test program failed to compile or link. See the file config.log for the
*** exact error that occured. This usually means LIBXML was incorrectly installed
*** or that you have moved LIBXML since it was installed. In the latter case, you
*** may want to edit the xml2-config script: /usr/bin/xml2-config
checking for library containing malloc_stats_print... no
checking for LIBSPDYLAY... no
configure: No package 'libspdylay' found
configure: The SPDY support in nghttpx and h2load will be disabled.
./configure: line 19526: syntax error near unexpected token `fi'
./configure: line 19526: `fi'
```

Only an idea: the creation of the .def file should be avoided. It would be cool when it has exports for the exported functions to build a shared library without def's.

**Comment by tatsuhiro-t** [comment]
Most checks in configure are for application under src or examples directories.
libnghttp2 itself has no dependency.  So simple Makefile could be written with predefined config.h for windows build.

**Comment by remoe** [comment]
I've tried to build with an changed Makefile.msvc:

- replaced the new files:
```
NGHTTP2_SRC = nghttp2_pq.c \
  nghttp2_map.c \
  nghttp2_queue.c \
  nghttp2_frame.c \
  nghttp2_buf.c \
  nghttp2_stream.c \
  nghttp2_outbound_item.c \
  nghttp2_session.c \
  nghttp2_submit.c \
  nghttp2_helper.c \
  nghttp2_npn.c \
  nghttp2_hd.c \
  nghttp2_hd_huffman.c \
  nghttp2_hd_huffman_data.c \
  nghttp2_version.c \
  nghttp2_priority_spec.c \
  nghttp2_option.c \
  nghttp2_callbacks.c \
  nghttp2_mem.c \
  nghttp2_http.c
```
- changed one define (_U_):
```CFLAGS   = -I./includes -I$(ZLIB_ROOT) -DHAVE_WINSOCK2_H -Dssize_t=long -D_U_="" ```
- creation of .def file doesn't work on my system:
```nm $(NGHTTP2_OBJ_R) | grep ' T .*_nghttp2' | sed 's/^.* _/  /' >> $@```
  the def file is empty:
```
; Generated by /cygdrive/g/sdk_src/nghttp2/lib/Makefile.MSVC. DO NOT EDIT.
;
LIBRARY nghttp2.dll
EXPORTS
NGHTTP2_STATIC_TABLE_LENGTH DATA
```
- the linker throws an error (I haven't found the issue):

```
link -nologo -machine:x64 -map -debug -incremental:no  -dll -out:nghttp2.dll -implib:nghttp2_imp.lib -def:MSVC_obj/r_nghttp2.def \
     MSVC_obj/r_nghttp2_pq.obj MSVC_obj/r_nghttp2_map.obj MSVC_obj/r_nghttp2_queue.obj MSVC_obj/r_nghttp2_frame.obj MSVC_obj/r_nghttp2_buf.obj MSVC_obj/r_nghttp
2_stream.obj MSVC_obj/r_nghttp2_outbound_item.obj MSVC_obj/r_nghttp2_session.obj MSVC_obj/r_nghttp2_submit.obj MSVC_obj/r_nghttp2_helper.obj MSVC_obj/r_nghttp2_
npn.obj MSVC_obj/r_nghttp2_hd.obj MSVC_obj/r_nghttp2_hd_huffman.obj MSVC_obj/r_nghttp2_hd_huffman_data.obj MSVC_obj/r_nghttp2_version.obj MSVC_obj/r_nghttp2_pri
ority_spec.obj MSVC_obj/r_nghttp2_option.obj MSVC_obj/r_nghttp2_callbacks.obj MSVC_obj/r_nghttp2_mem.obj MSVC_obj/r_nghttp2_http.obj MSVC_obj/r_nghttp2.res g:/s
dk/zlib/1.2.8/win/64/release/lib/zlib.lib ws2_32.lib
link: unknown option -- n
Try 'link --help' for more information.
Makefile.msvc:122: recipe for target 'nghttp2.dll' failed
make: *** [nghttp2.dll] Error 1
```

**Comment by tatsuhiro-t** [comment]
I don't know much about MSVC tooling, but I think last linker error is caused by invocation of "link" program which call the link function to create a link to a file (usually comes with *nix) instead of linker command.

**Comment by tatsuhiro-t** [comment]
Also I noticed that zlib is no longer required to build libnghttp2 now.

**Comment by remoe** [comment]
yea, thanks, I also find this out with link :)

**Comment by remoe** [comment]
Ok, I can build it now, but with no exports. Do you have a working .def file? Then I can try to fix the makefile.

**Comment by tatsuhiro-t** [comment]
No, I don't have one. Is there any switch to make everything export just for now?

**Comment by tatsuhiro-t** [comment]
Probably the output of "nm $(NGHTTP2_OBJ_R)" may be different from one which the author of this makefile saw.  Adjusting grep pattern and sed script may enable def file creation.

**Comment by remoe** [comment]
yes, I know. nm is not nm ?! :)

I see this output:

```
0000000000001620 T nghttp2_frame_window_update_free
00000000000015c0 T nghttp2_frame_window_update_init
                 U nghttp2_get_uint16
                 U nghttp2_get_uint32
                 U nghttp2_hd_deflate_hd_bufs
0000000000001ae0 T nghttp2_iv_check
                 U nghttp2_mem_free
                 U nghttp2_mem_malloc
00000000000017a0 T nghttp2_nv_array_copy
0000000000001ab0 T nghttp2_nv_array_del
0000000000001760 T nghttp2_nv_array_sort
```

and this make no sense for me:

```
nm $(NGHTTP2_OBJ_R) | grep ' T .*_nghttp2' | sed 's/^.* _/  /' >> $@
```

**Comment by tatsuhiro-t** [comment]
I got same output on linux.  If you change the patterns, does it work?

**Comment by remoe** [comment]
It builds and export functions. But I need to test linking with curl.

**Comment by tatsuhiro-t** [comment]
OK.
As you suggested in the first post, it would be easier to add __declspec(dllexport) wrapped by a macro to public API function for windows build.
I think we can further remove winsock2 dependency since the only functions we use are ntoh{s,l}/hton{s,l}.

**Comment by remoe** [comment]
Ok, I try to link with curl 0.7.41:

```
1>http2.obj : error LNK2019: unresolved external symbol _nghttp2_session_callbacks_new referenced in function _Curl_http2_init
1>http2.obj : error LNK2019: unresolved external symbol _nghttp2_session_callbacks_del referenced in function _Curl_http2_init
1>http2.obj : error LNK2019: unresolved external symbol _nghttp2_session_callbacks_set_send_callback referenced in function _Curl_http2_init
```

So, something is wrong with it.

**Comment by remoe** [comment]
the master branch builds with VS2013 / x64 on curl 0.7.41! Should I PR the changed Makefile.msvc?

**Comment by tatsuhiro-t** [comment]
Great! and Yes, please submit PR.

Meanwhile, I made a commi 966e3a1t to add __declspec(dllexport) to public function.
That could eliminate .def file.

**Comment by remoe** [comment]
Sorry, I had some "lag" :) curl doesn't build nghttp2 on windows without modification of build files ?! Here is the output of a curl windows x64 binary:

```
curl 7.42.0-DEV (x86_64-pc-win32) libcurl/7.42.0-DEV zlib/1.2.8 WinIDN nghttp2/0.7.10
Protocols: dict file ftp gopher http imap ldap pop3 rtsp smb smtp telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM libz HTTP2
```
So I think it would work ;)

**Comment by remoe** [comment]
Ok, I hope it is usable :)

https://github.com/tatsuhiro-t/nghttp2/pull/196

**Comment by tatsuhiro-t** [comment]
Thanks. PR merged. I think this issue can be closed now.

**Comment by whitekyo** [comment]
> Ok, I hope it is usable :)
> 
> #196

I change the Makefile.msvc to https://github.com/remoe/nghttp2/blob/0312521ac94fb073ca6b80bcfae06a6e46a4fe67/lib/Makefile.msvc 

but it's still work
