### ISSUE TITLE
Unable to compile on Ubuntu 14.10

### ISSUE THREAD

**Issue by webeau** [tatsuhiro-t/nghttp2#256]
I have met all the build requirements and followed the build instructions from the README document including the spdylay compilation.

When I try get to the 'make', I get the following error:

h2load.cc: In function âvoid h2load::{anonymous}::print_server_tmp_key(SSL*)â:
h2load.cc:298:40: error: âSSL_get_server_tmp_keyâ was not declared in this scope
   if (!SSL_get_server_tmp_key(ssl, &key)) {
                                        ^
h2load.cc:317:39: error: âEC_curve_nid2nistâ was not declared in this scope
     auto cname = EC_curve_nid2nist(nid);
                                       ^
Not sure what is up here.  I used the apt-get provided in the instructions but I have also compiled libressl on this server.  Is that a possible issue?  If so, I am unclear on how to use the original openssl installed with apt-get in /usr/lib rather than the libressl library.

**Comment by tatsuhiro-t** [comment]
Latest master branch should compile with LibreSSL (at least 2.2.0) now.

**Comment by webeau** [comment]
I can verify that it now compiles.
